### ISSUE TITLE
Using OpenCV in Python on Jetson Nano. Import cv2 in virtual env not working after install.

### ISSUE THREAD

**Issue by devedse** [jetsonhacks/buildOpenCVXavier#2]
Hi @jetsonhacks ,

I've successfully installed this setup on the Jetson Nano. It now also works on the default python environment. However what I would like to do is also add it to my "virtual_env".

Do you have any idea on how to do this? I've been searching the internet but can't really find a solution for it.

Someone mentioned I should copy paste the *cv*.so files into the Virtual Env folder, but that didn't fix the issue either.

**Comment by devedse** [comment]
Update:
I managed to fix this issue by copying:
```
/usr/local/lib/python3.6/dist-packages/cv2.cpython-36m-aarch64-linux-gnu.so
to
/home/avanade/.virtualenvs/deep_learning/lib/python3.6/site-packages/cv2.cpython-36m-aarch64-linux-gnu.so
```

**Comment by NikolaAndro** [comment]
> Update: I managed to fix this issue by copying:
> 
> ```
> /usr/local/lib/python3.6/dist-packages/cv2.cpython-36m-aarch64-linux-gnu.so
> to
> /home/avanade/.virtualenvs/deep_learning/lib/python3.6/site-packages/cv2.cpython-36m-aarch64-linux-gnu.so
> ```

@devedse Thank you soooo much!!!!! It did solve the problem!
